# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93a3794c1977b8450a9e944c603ed8dc881ef376e42c755c700e0e3f9b46757412b62b9ecae17307a2b4235f60cdc8aea174283760b76654be9d49dd6c51e3ba

test:
  secret_key_base: 04f66c68e0c524c3ee11386b258b676a0a21fccda1efd7c8c142ee7b276eab464dd3444ec78f44dff158ddf199104228237e4670e5c56c05a75dccd6f1885f3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
